### ISSUE TITLE
Crash while punching Evolved Enderman [1.12.2]

### ISSUE THREAD

**Issue by CobaltRealm** [p455w0rd/EndermanEvolution#4] opened 2018-01-13 20:10 UTC
https://gist.github.com/p455w0rd/4673e1d895f54727d1eeea89568c05eb

**Comment by p455w0rd** [comment] 2018-01-13 20:17
Please look into a paste service like github gist or pastebin rather than flooding issue trackers..at any rate, the issue is here: https://github.com/Insane-96/VulcaniteMod/blob/master/common/net/insane96mcp/vulcanite/events/LivingHurt.java#L80 ..they are assuming the player will be server side..they could annotate with `@SideOnly(Side.SERVER)` or just do an instanceof check..please contact this mod dev and report back if the author resolves the situation

**Comment by p455w0rd** [comment] 2018-01-25 18:43
this was fixed on their end

**Closed as completed by p455w0rd** 2018-01-25 18:43 UTC
Labels: fixed
