### ISSUE TITLE
Evolved Enderman are ignoring light level for spawn

### ISSUE THREAD

**Issue by SummitSummit** [p455w0rd/EndermanEvolution#20] opened 2018-03-07 20:39 UTC
Evolved Enderman are ignoring light level for spawn even while:
   # Allow Evolved Enderman to spawn at any light level [default: true]
   B:EndermanSpawnIgnoreLightLevel=false
Version 1.0.11
MC 1.12.2

**Comment by p455w0rd** [comment] 2018-03-07 20:42
this has to be mod interaction...tested and they do not spawn when that config is set to false....if you want to discuss this further, please join my discord https://discord.gg/9J7yhUP

**Comment by p455w0rd** [comment] 2018-03-14 12:45
closing because I'm unable to reproduce and no further discussion has occured

**Closed as completed by p455w0rd** 2018-03-14 12:45 UTC
